CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(190) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    headline VARCHAR(255),
    bio TEXT,
    city VARCHAR(120),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE creator_profiles (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    slug VARCHAR(190) NOT NULL UNIQUE,
    mood VARCHAR(120),
    cover_style VARCHAR(80),
    featured BOOLEAN NOT NULL DEFAULT FALSE,
    followers INTEGER NOT NULL DEFAULT 0,
    rating NUMERIC(3,1) NOT NULL DEFAULT 5.0
);

CREATE TABLE content_items (
    id BIGSERIAL PRIMARY KEY,
    creator_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(190) NOT NULL,
    excerpt TEXT,
    body TEXT,
    visibility VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    kind VARCHAR(40) NOT NULL,
    moderation_feedback TEXT,
    saved_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE plans (
    id BIGSERIAL PRIMARY KEY,
    creator_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(120) NOT NULL,
    description TEXT,
    price_tokens INTEGER NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    perks JSONB NOT NULL DEFAULT '[]'::jsonb
);

CREATE TABLE subscriptions (
    id BIGSERIAL PRIMARY KEY,
    subscriber_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    creator_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    plan_id BIGINT NOT NULL REFERENCES plans(id) ON DELETE CASCADE,
    status VARCHAR(30) NOT NULL,
    renews_at TIMESTAMP
);

CREATE TABLE live_sessions (
    id BIGSERIAL PRIMARY KEY,
    creator_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(190) NOT NULL,
    description TEXT,
    status VARCHAR(30) NOT NULL,
    scheduled_for TIMESTAMP,
    viewer_count INTEGER NOT NULL DEFAULT 0,
    price_tokens INTEGER NOT NULL DEFAULT 0,
    chat_enabled BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE favorites (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    creator_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE saved_items (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    content_id BIGINT NOT NULL REFERENCES content_items(id) ON DELETE CASCADE
);

CREATE TABLE conversations (
    id BIGSERIAL PRIMARY KEY,
    subscriber_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    creator_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE messages (
    id BIGSERIAL PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    body TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE live_messages (
    id BIGSERIAL PRIMARY KEY,
    live_id BIGINT NOT NULL REFERENCES live_sessions(id) ON DELETE CASCADE,
    sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    body TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE wallet_transactions (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type VARCHAR(50) NOT NULL,
    direction VARCHAR(10) NOT NULL,
    amount INTEGER NOT NULL,
    note TEXT,
    creator_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    subscriber_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE settings (
    key VARCHAR(80) PRIMARY KEY,
    value JSONB NOT NULL
);
